version: '3.4'

networks:
  tasktracker-dev:
    driver: bridge 

services:
  tasktracker:
    image: tasktracker:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image; port=5432; Database=tasktracker; Username=postgres; Password=postgres"
    networks:
      - tasktracker-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      # - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tasktracker"
    networks:
      - tasktracker-dev
volumes:
  db_volume:
